
CREATE OR REPLACE FUNCTION public.derive_trim_class(
  p_make TEXT,
  p_model TEXT,
  p_variant TEXT
)
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
  m TEXT := UPPER(TRIM(p_make));
  mo TEXT := UPPER(TRIM(p_model));
  v TEXT := UPPER(COALESCE(p_variant, ''));
BEGIN
  -- TOYOTA LANDCRUISER 70 SERIES
  IF m = 'TOYOTA' AND mo = 'LANDCRUISER' THEN
    IF v LIKE '%WORKMATE%' THEN RETURN 'LC70_BASE';
    ELSIF v LIKE '%GXL%' THEN RETURN 'LC70_GXL';
    ELSIF v LIKE '%GX%' THEN RETURN 'LC70_GX';
    ELSIF v LIKE '%VX%' THEN RETURN 'LC70_VX';
    ELSIF v LIKE '%SAHARA%' THEN RETURN 'LC70_SAHARA';
    ELSIF v LIKE '%70TH%' THEN RETURN 'LC70_SPECIAL';
    END IF;
  END IF;

  -- LANDCRUISER 200
  IF m = 'TOYOTA' AND mo = 'LANDCRUISER 200' THEN
    IF v LIKE '%GXL%' THEN RETURN 'LC200_GXL';
    ELSIF v LIKE '%GX%' THEN RETURN 'LC200_GX';
    ELSIF v LIKE '%VX%' THEN RETURN 'LC200_VX';
    ELSIF v LIKE '%SAHARA%' THEN RETURN 'LC200_SAHARA';
    END IF;
  END IF;

  -- LANDCRUISER 300
  IF m = 'TOYOTA' AND mo = 'LANDCRUISER 300' THEN
    IF v LIKE '%GXL%' THEN RETURN 'LC300_GXL';
    ELSIF v LIKE '%GX%' THEN RETURN 'LC300_GX';
    ELSIF v LIKE '%VX%' THEN RETURN 'LC300_VX';
    ELSIF v LIKE '%SAHARA%' THEN RETURN 'LC300_SAHARA';
    END IF;
  END IF;

  -- PRADO
  IF m = 'TOYOTA' AND mo LIKE '%PRADO%' THEN
    IF v LIKE '%GXL%' THEN RETURN 'PRADO_GXL';
    ELSIF v LIKE '%GX%' THEN RETURN 'PRADO_GX';
    ELSIF v LIKE '%VX%' THEN RETURN 'PRADO_VX';
    ELSIF v LIKE '%KAKADU%' THEN RETURN 'PRADO_KAKADU';
    END IF;
  END IF;

  -- HILUX
  IF m = 'TOYOTA' AND mo = 'HILUX' THEN
    IF v LIKE '%SR5%' THEN RETURN 'HILUX_SR5';
    ELSIF v LIKE '%SR%' THEN RETURN 'HILUX_SR';
    ELSIF v LIKE '%ROGUE%' THEN RETURN 'HILUX_ROGUE';
    ELSIF v LIKE '%RUGGED%' THEN RETURN 'HILUX_RUGGED';
    ELSIF v LIKE '%WORKMATE%' THEN RETURN 'HILUX_BASE';
    END IF;
  END IF;

  -- FORD RANGER
  IF m = 'FORD' AND mo = 'RANGER' THEN
    IF v LIKE '%RAPTOR%' THEN RETURN 'RANGER_RAPTOR';
    ELSIF v LIKE '%WILDTRAK%' THEN RETURN 'RANGER_WILDTRAK';
    ELSIF v LIKE '%XLT%' THEN RETURN 'RANGER_XLT';
    ELSIF v LIKE '%XLS%' THEN RETURN 'RANGER_XLS';
    ELSIF v LIKE '%XL%' THEN RETURN 'RANGER_XL';
    END IF;
  END IF;

  -- FORD EVEREST
  IF m = 'FORD' AND mo = 'EVEREST' THEN
    IF v LIKE '%TITANIUM%' THEN RETURN 'EVEREST_TITANIUM';
    ELSIF v LIKE '%TREND%' THEN RETURN 'EVEREST_TREND';
    ELSIF v LIKE '%AMBIENTE%' THEN RETURN 'EVEREST_AMBIENTE';
    END IF;
  END IF;

  -- ISUZU D-MAX
  IF m = 'ISUZU' AND (mo = 'D-MAX' OR mo = 'DMAX') THEN
    IF v LIKE '%X-TERRAIN%' OR v LIKE '%XTERRAIN%' THEN RETURN 'DMAX_XTERRAIN';
    ELSIF v LIKE '%LS-U%' OR v LIKE '%LSU%' THEN RETURN 'DMAX_LSU';
    ELSIF v LIKE '%LS-M%' OR v LIKE '%LSM%' THEN RETURN 'DMAX_LSM';
    ELSIF v LIKE '%SX%' THEN RETURN 'DMAX_SX';
    END IF;
  END IF;

  -- ISUZU MU-X
  IF m = 'ISUZU' AND (mo = 'MU-X' OR mo = 'MUX') THEN
    IF v LIKE '%LS-T%' OR v LIKE '%LST%' THEN RETURN 'MUX_LST';
    ELSIF v LIKE '%LS-U%' OR v LIKE '%LSU%' THEN RETURN 'MUX_LSU';
    ELSIF v LIKE '%LS-M%' OR v LIKE '%LSM%' THEN RETURN 'MUX_LSM';
    END IF;
  END IF;

  -- MITSUBISHI TRITON
  IF m = 'MITSUBISHI' AND mo = 'TRITON' THEN
    IF v LIKE '%GLS%' THEN RETURN 'TRITON_GLS';
    ELSIF v LIKE '%GLX+%' OR v LIKE '%GLX PLUS%' THEN RETURN 'TRITON_GLXPLUS';
    ELSIF v LIKE '%GLX%' THEN RETURN 'TRITON_GLX';
    END IF;
  END IF;

  -- NISSAN NAVARA
  IF m = 'NISSAN' AND mo = 'NAVARA' THEN
    IF v LIKE '%PRO-4X%' OR v LIKE '%PRO4X%' THEN RETURN 'NAVARA_PRO4X';
    ELSIF v LIKE '%ST-X%' OR v LIKE '%STX%' THEN RETURN 'NAVARA_STX';
    ELSIF v LIKE '%ST-L%' OR v LIKE '%STL%' THEN RETURN 'NAVARA_STL';
    ELSIF v LIKE '%ST%' THEN RETURN 'NAVARA_ST';
    ELSIF v LIKE '%SL%' THEN RETURN 'NAVARA_SL';
    END IF;
  END IF;

  -- NISSAN PATROL
  IF m = 'NISSAN' AND mo = 'PATROL' THEN
    IF v LIKE '%TI-L%' OR v LIKE '%TIL%' THEN RETURN 'PATROL_TIL';
    ELSIF v LIKE '%TI%' THEN RETURN 'PATROL_TI';
    END IF;
  END IF;

  -- Default fallback
  RETURN mo || '_STANDARD';
END;
$$;
