-- ============================================================================
-- MORNING BRIEF ITEMS
-- Stores the daily prioritised auction buy list generated by the
-- morning-brief edge function (runs at 6am AEST = 20:00 UTC).
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.morning_brief_items (
  id                      uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  listing_id              text NOT NULL,
  brief_date              date NOT NULL,

  -- Vehicle identity
  make                    text,
  model                   text,
  year                    integer,
  km                      integer,
  variant                 text,
  fuel                    text,
  transmission            text,
  drivetrain              text,

  -- Pricing
  asking_price            numeric,
  guide_price             numeric,
  reserve_price           numeric,
  buy_method              text,

  -- Auction timing
  sale_close_at           timestamptz,
  sale_status             text,
  reserve_status          text,

  -- Source
  source                  text,
  location                text,
  state                   text,
  listing_url             text,
  auction_house           text,

  -- Condition flags
  wovr_indicator          boolean,
  damage_noted            boolean,
  condition_notes         text[],
  keys_present            boolean,
  starts_drives           boolean,

  -- Scoring (from operator_opportunities)
  tier                    text,
  expected_margin         numeric,
  under_buy               numeric,
  retail_median           numeric,
  retail_median_confidence text,
  guide_vs_median_gap     numeric,
  auction_target_price    numeric,
  motivation_signal       text,
  margin_flag             text,

  -- Spec matching
  matched_spec_names      text[] DEFAULT '{}',

  -- Composite ranking score
  composite_score         integer DEFAULT 0,

  -- Metadata
  created_at              timestamptz DEFAULT now(),
  updated_at              timestamptz DEFAULT now(),

  UNIQUE (listing_id, brief_date)
);

-- Index for daily brief queries
CREATE INDEX IF NOT EXISTS idx_morning_brief_items_brief_date
  ON public.morning_brief_items (brief_date DESC, composite_score DESC);

CREATE INDEX IF NOT EXISTS idx_morning_brief_items_tier
  ON public.morning_brief_items (tier, brief_date DESC);

CREATE INDEX IF NOT EXISTS idx_morning_brief_items_sale_close
  ON public.morning_brief_items (sale_close_at ASC);

-- RLS
ALTER TABLE public.morning_brief_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Operators can read morning_brief_items"
  ON public.morning_brief_items FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Service role can manage morning_brief_items"
  ON public.morning_brief_items FOR ALL
  TO service_role
  USING (true);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION public.update_morning_brief_items_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER morning_brief_items_updated_at
  BEFORE UPDATE ON public.morning_brief_items
  FOR EACH ROW EXECUTE FUNCTION public.update_morning_brief_items_updated_at();

-- ============================================================================
-- CRON: Run morning-brief at 6am AEST (20:00 UTC) Mon–Fri
-- ============================================================================
SELECT cron.schedule(
  'morning-brief',
  '0 20 * * 1-5',  -- 20:00 UTC = 06:00 AEST (UTC+10)
  $$
  SELECT net.http_post(
    url := (SELECT value FROM app_config WHERE key = 'supabase_functions_url') || '/morning-brief',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || (SELECT value FROM app_config WHERE key = 'service_role_key')
    ),
    body := '{}'::jsonb
  );
  $$
);
