
-- Expand derive_trim_from_text with additional models
CREATE OR REPLACE FUNCTION public.derive_trim_from_text(p_make TEXT, p_model TEXT, p_description TEXT DEFAULT NULL)
RETURNS TEXT
LANGUAGE plpgsql IMMUTABLE
SET search_path = public
AS $$
DECLARE
  m TEXT := UPPER(TRIM(COALESCE(p_make,'')));
  mo TEXT := UPPER(TRIM(COALESCE(p_model,'')));
  d TEXT := UPPER(COALESCE(p_description,''));
BEGIN

  -- TOYOTA LANDCRUISER
  IF m = 'TOYOTA' AND mo = 'LANDCRUISER' THEN
    IF d LIKE '%WORKMATE%' THEN RETURN 'WORKMATE'; END IF;
    IF d LIKE '%GXL%' THEN RETURN 'GXL'; END IF;
    IF d LIKE '%GX%' THEN RETURN 'GX'; END IF;
    IF d LIKE '%VX%' THEN RETURN 'VX'; END IF;
    IF d LIKE '%SAHARA%' THEN RETURN 'SAHARA'; END IF;
    RETURN 'BASE';
  END IF;

  -- PRADO
  IF m = 'TOYOTA' AND mo LIKE '%PRADO%' THEN
    IF d LIKE '%KAKADU%' THEN RETURN 'KAKADU'; END IF;
    IF d LIKE '%GXL%' THEN RETURN 'GXL'; END IF;
    IF d LIKE '%GX%' THEN RETURN 'GX'; END IF;
    IF d LIKE '%VX%' THEN RETURN 'VX'; END IF;
    RETURN 'BASE';
  END IF;

  -- HILUX
  IF m = 'TOYOTA' AND mo = 'HILUX' THEN
    IF d LIKE '%ROGUE%' THEN RETURN 'ROGUE'; END IF;
    IF d LIKE '%RUGGED%' THEN RETURN 'RUGGED'; END IF;
    IF d LIKE '%SR5%' THEN RETURN 'SR5'; END IF;
    IF d LIKE '%WORKMATE%' THEN RETURN 'WORKMATE'; END IF;
    IF d ~ '\mSR\M' THEN RETURN 'SR'; END IF;
    RETURN 'BASE';
  END IF;

  -- RAV4
  IF m = 'TOYOTA' AND mo = 'RAV4' THEN
    IF d LIKE '%EDGE%' THEN RETURN 'EDGE'; END IF;
    IF d LIKE '%CRUISER%' THEN RETURN 'CRUISER'; END IF;
    IF d LIKE '%GXL%' THEN RETURN 'GXL'; END IF;
    IF d LIKE '%GX%' THEN RETURN 'GX'; END IF;
    RETURN 'BASE';
  END IF;

  -- KLUGER
  IF m = 'TOYOTA' AND mo = 'KLUGER' THEN
    IF d LIKE '%GRANDE%' THEN RETURN 'GRANDE'; END IF;
    IF d LIKE '%GXL%' THEN RETURN 'GXL'; END IF;
    IF d LIKE '%GX%' THEN RETURN 'GX'; END IF;
    RETURN 'BASE';
  END IF;

  -- HIACE
  IF m = 'TOYOTA' AND mo LIKE '%HIACE%' THEN
    IF d LIKE '%COMMUTER%' THEN RETURN 'COMMUTER'; END IF;
    IF d LIKE '%SLWB%' THEN RETURN 'SLWB'; END IF;
    IF d LIKE '%LWB%' THEN RETURN 'LWB'; END IF;
    RETURN 'BASE';
  END IF;

  -- COROLLA
  IF m = 'TOYOTA' AND mo = 'COROLLA' THEN
    IF d LIKE '%ZR%' THEN RETURN 'ZR'; END IF;
    IF d LIKE '%SX%' THEN RETURN 'SX'; END IF;
    IF d LIKE '%ASCENT SPORT%' THEN RETURN 'ASCENT SPORT'; END IF;
    IF d LIKE '%ASCENT%' THEN RETURN 'ASCENT'; END IF;
    RETURN 'BASE';
  END IF;

  -- FORD RANGER
  IF m = 'FORD' AND mo = 'RANGER' THEN
    IF d LIKE '%RAPTOR%' THEN RETURN 'RAPTOR'; END IF;
    IF d LIKE '%WILDTRAK%' THEN RETURN 'WILDTRAK'; END IF;
    IF d LIKE '%XLT%' THEN RETURN 'XLT'; END IF;
    IF d LIKE '%XLS%' THEN RETURN 'XLS'; END IF;
    IF d ~ '\mXL\M' THEN RETURN 'XL'; END IF;
    RETURN 'BASE';
  END IF;

  -- FORD EVEREST
  IF m = 'FORD' AND mo = 'EVEREST' THEN
    IF d LIKE '%TREMOR%' THEN RETURN 'TREMOR'; END IF;
    IF d LIKE '%PLATINUM%' THEN RETURN 'PLATINUM'; END IF;
    IF d LIKE '%SPORT%' THEN RETURN 'SPORT'; END IF;
    IF d LIKE '%TITANIUM%' THEN RETURN 'TITANIUM'; END IF;
    IF d LIKE '%TREND%' THEN RETURN 'TREND'; END IF;
    IF d LIKE '%AMBIENTE%' THEN RETURN 'AMBIENTE'; END IF;
    RETURN 'BASE';
  END IF;

  -- FORD FOCUS
  IF m = 'FORD' AND mo = 'FOCUS' THEN
    IF d LIKE '%TITANIUM%' THEN RETURN 'TITANIUM'; END IF;
    IF d LIKE '%TREND%' THEN RETURN 'TREND'; END IF;
    IF d LIKE '%SPORT%' THEN RETURN 'SPORT'; END IF;
    IF d LIKE '%AMBIENTE%' THEN RETURN 'AMBIENTE'; END IF;
    RETURN 'BASE';
  END IF;

  -- FORD TRANSIT / TRANSIT CUSTOM
  IF m = 'FORD' AND mo LIKE '%TRANSIT%' THEN
    RETURN 'BASE';
  END IF;

  -- MAZDA BT-50
  IF m = 'MAZDA' AND (mo = 'BT-50' OR mo = 'BT50') THEN
    IF d LIKE '%XTR%' THEN RETURN 'XTR'; END IF;
    IF d ~ '\mXT\M' THEN RETURN 'XT'; END IF;
    IF d ~ '\mGT\M' THEN RETURN 'GT'; END IF;
    RETURN 'BASE';
  END IF;

  -- MAZDA CX-5
  IF m = 'MAZDA' AND (mo = 'CX-5' OR mo = 'CX5') THEN
    IF d LIKE '%AKERA%' THEN RETURN 'AKERA'; END IF;
    IF d LIKE '%GT%' THEN RETURN 'GT'; END IF;
    IF d LIKE '%TOURING%' THEN RETURN 'TOURING'; END IF;
    IF d LIKE '%MAXX SPORT%' THEN RETURN 'MAXX SPORT'; END IF;
    IF d LIKE '%MAXX%' THEN RETURN 'MAXX'; END IF;
    RETURN 'BASE';
  END IF;

  -- MAZDA CX-9
  IF m = 'MAZDA' AND (mo = 'CX-9' OR mo = 'CX9') THEN
    IF d LIKE '%AZAMI%' THEN RETURN 'AZAMI'; END IF;
    IF d LIKE '%GT%' THEN RETURN 'GT'; END IF;
    IF d LIKE '%TOURING%' THEN RETURN 'TOURING'; END IF;
    IF d LIKE '%SPORT%' THEN RETURN 'SPORT'; END IF;
    RETURN 'BASE';
  END IF;

  -- MAZDA 3
  IF m = 'MAZDA' AND mo = '3' THEN
    IF d LIKE '%SP25%' THEN RETURN 'SP25'; END IF;
    IF d LIKE '%MAXX SPORT%' THEN RETURN 'MAXX SPORT'; END IF;
    IF d LIKE '%MAXX%' THEN RETURN 'MAXX'; END IF;
    IF d LIKE '%NEO%' THEN RETURN 'NEO'; END IF;
    RETURN 'BASE';
  END IF;

  -- VOLKSWAGEN AMAROK
  IF m = 'VOLKSWAGEN' AND mo = 'AMAROK' THEN
    IF d LIKE '%PANAMERICANA%' THEN RETURN 'PANAMERICANA'; END IF;
    IF d LIKE '%AVENTURA%' THEN RETURN 'AVENTURA'; END IF;
    IF d LIKE '%TDI550%' THEN RETURN 'TDI550'; END IF;
    IF d LIKE '%TDI400%' THEN RETURN 'TDI400'; END IF;
    IF d LIKE '%CORE%' THEN RETURN 'CORE'; END IF;
    RETURN 'BASE';
  END IF;

  -- VOLKSWAGEN GOLF
  IF m = 'VOLKSWAGEN' AND mo = 'GOLF' THEN
    IF d LIKE '%GTI%' THEN RETURN 'GTI'; END IF;
    IF d ~ '\mR\M' THEN RETURN 'R'; END IF;
    IF d LIKE '%HIGHLINE%' THEN RETURN 'HIGHLINE'; END IF;
    IF d LIKE '%COMFORTLINE%' THEN RETURN 'COMFORTLINE'; END IF;
    IF d LIKE '%TRENDLINE%' THEN RETURN 'TRENDLINE'; END IF;
    RETURN 'BASE';
  END IF;

  -- VOLKSWAGEN TIGUAN
  IF m = 'VOLKSWAGEN' AND mo = 'TIGUAN' THEN
    IF d LIKE '%R-LINE%' THEN RETURN 'R-LINE'; END IF;
    IF d LIKE '%HIGHLINE%' THEN RETURN 'HIGHLINE'; END IF;
    IF d LIKE '%COMFORTLINE%' THEN RETURN 'COMFORTLINE'; END IF;
    IF d LIKE '%TRENDLINE%' THEN RETURN 'TRENDLINE'; END IF;
    RETURN 'BASE';
  END IF;

  -- VOLKSWAGEN PASSAT
  IF m = 'VOLKSWAGEN' AND mo = 'PASSAT' THEN
    IF d LIKE '%R-LINE%' THEN RETURN 'R-LINE'; END IF;
    IF d LIKE '%HIGHLINE%' THEN RETURN 'HIGHLINE'; END IF;
    IF d LIKE '%COMFORTLINE%' THEN RETURN 'COMFORTLINE'; END IF;
    RETURN 'BASE';
  END IF;

  -- NISSAN PATROL
  IF m = 'NISSAN' AND mo = 'PATROL' THEN
    IF d LIKE '%TI-L%' OR d LIKE '%TIL%' THEN RETURN 'TI-L'; END IF;
    IF d ~ '\mTI\M' THEN RETURN 'TI'; END IF;
    IF d LIKE '%ST-L%' OR d LIKE '%STL%' THEN RETURN 'ST-L'; END IF;
    IF d ~ '\mST\M' THEN RETURN 'ST'; END IF;
    RETURN 'BASE';
  END IF;

  -- NISSAN NAVARA
  IF m = 'NISSAN' AND mo = 'NAVARA' THEN
    IF d LIKE '%PRO-4X%' OR d LIKE '%PRO4X%' THEN RETURN 'PRO-4X'; END IF;
    IF d LIKE '%ST-X%' OR d LIKE '%STX%' THEN RETURN 'ST-X'; END IF;
    IF d LIKE '%ST-L%' OR d LIKE '%STL%' THEN RETURN 'ST-L'; END IF;
    IF d ~ '\mST\M' THEN RETURN 'ST'; END IF;
    IF d ~ '\mSL\M' THEN RETURN 'SL'; END IF;
    RETURN 'BASE';
  END IF;

  -- NISSAN X-TRAIL
  IF m = 'NISSAN' AND (mo = 'X-TRAIL' OR mo = 'XTRAIL') THEN
    IF d LIKE '%TI%' THEN RETURN 'TI'; END IF;
    IF d LIKE '%ST-L%' OR d LIKE '%STL%' THEN RETURN 'ST-L'; END IF;
    IF d ~ '\mST\M' THEN RETURN 'ST'; END IF;
    RETURN 'BASE';
  END IF;

  -- NISSAN PATHFINDER
  IF m = 'NISSAN' AND mo = 'PATHFINDER' THEN
    IF d LIKE '%TI%' THEN RETURN 'TI'; END IF;
    IF d LIKE '%ST-L%' OR d LIKE '%STL%' THEN RETURN 'ST-L'; END IF;
    IF d ~ '\mST\M' THEN RETURN 'ST'; END IF;
    RETURN 'BASE';
  END IF;

  -- NISSAN QASHQAI
  IF m = 'NISSAN' AND mo = 'QASHQAI' THEN
    IF d LIKE '%TI%' THEN RETURN 'TI'; END IF;
    IF d LIKE '%ST-L%' OR d LIKE '%STL%' THEN RETURN 'ST-L'; END IF;
    IF d ~ '\mST\M' THEN RETURN 'ST'; END IF;
    RETURN 'BASE';
  END IF;

  -- MITSUBISHI TRITON
  IF m = 'MITSUBISHI' AND mo = 'TRITON' THEN
    IF d LIKE '%GLS%' THEN RETURN 'GLS'; END IF;
    IF d LIKE '%GLX+%' OR d LIKE '%GLX PLUS%' THEN RETURN 'GLX+'; END IF;
    IF d LIKE '%GLX%' THEN RETURN 'GLX'; END IF;
    RETURN 'BASE';
  END IF;

  -- MITSUBISHI OUTLANDER
  IF m = 'MITSUBISHI' AND mo = 'OUTLANDER' THEN
    IF d LIKE '%EXCEED%' THEN RETURN 'EXCEED'; END IF;
    IF d LIKE '%ASPIRE%' THEN RETURN 'ASPIRE'; END IF;
    IF d LIKE '%LS%' THEN RETURN 'LS'; END IF;
    IF d LIKE '%ES%' THEN RETURN 'ES'; END IF;
    RETURN 'BASE';
  END IF;

  -- MITSUBISHI PAJERO SPORT
  IF m = 'MITSUBISHI' AND mo LIKE '%PAJERO%SPORT%' THEN
    IF d LIKE '%EXCEED%' THEN RETURN 'EXCEED'; END IF;
    IF d LIKE '%GLS%' THEN RETURN 'GLS'; END IF;
    IF d LIKE '%GLX%' THEN RETURN 'GLX'; END IF;
    RETURN 'BASE';
  END IF;

  -- MITSUBISHI ECLIPSE CROSS
  IF m = 'MITSUBISHI' AND mo LIKE '%ECLIPSE%' THEN
    IF d LIKE '%EXCEED%' THEN RETURN 'EXCEED'; END IF;
    IF d LIKE '%ASPIRE%' THEN RETURN 'ASPIRE'; END IF;
    IF d LIKE '%LS%' THEN RETURN 'LS'; END IF;
    IF d LIKE '%ES%' THEN RETURN 'ES'; END IF;
    RETURN 'BASE';
  END IF;

  -- ISUZU D-MAX
  IF m = 'ISUZU' AND (mo = 'D-MAX' OR mo = 'DMAX') THEN
    IF d LIKE '%X-TERRAIN%' OR d LIKE '%XTERRAIN%' THEN RETURN 'X-TERRAIN'; END IF;
    IF d LIKE '%LS-U%' OR d LIKE '%LSU%' THEN RETURN 'LS-U'; END IF;
    IF d LIKE '%LS-M%' OR d LIKE '%LSM%' THEN RETURN 'LS-M'; END IF;
    IF d LIKE '%SX%' THEN RETURN 'SX'; END IF;
    RETURN 'BASE';
  END IF;

  -- ISUZU MU-X
  IF m = 'ISUZU' AND (mo = 'MU-X' OR mo = 'MUX') THEN
    IF d LIKE '%LS-T%' OR d LIKE '%LST%' THEN RETURN 'LS-T'; END IF;
    IF d LIKE '%LS-U%' OR d LIKE '%LSU%' THEN RETURN 'LS-U'; END IF;
    IF d LIKE '%LS-M%' OR d LIKE '%LSM%' THEN RETURN 'LS-M'; END IF;
    RETURN 'BASE';
  END IF;

  -- JEEP GRAND CHEROKEE
  IF m = 'JEEP' AND mo LIKE '%GRAND CHEROKEE%' THEN
    IF d LIKE '%TRACKHAWK%' THEN RETURN 'TRACKHAWK'; END IF;
    IF d LIKE '%SRT%' THEN RETURN 'SRT'; END IF;
    IF d LIKE '%SUMMIT%' THEN RETURN 'SUMMIT'; END IF;
    IF d LIKE '%OVERLAND%' THEN RETURN 'OVERLAND'; END IF;
    IF d LIKE '%LIMITED%' THEN RETURN 'LIMITED'; END IF;
    IF d LIKE '%LAREDO%' THEN RETURN 'LAREDO'; END IF;
    RETURN 'BASE';
  END IF;

  -- SUBARU FORESTER
  IF m = 'SUBARU' AND mo = 'FORESTER' THEN
    IF d LIKE '%S-EDITION%' THEN RETURN 'S-EDITION'; END IF;
    IF d LIKE '%2.5I-S%' THEN RETURN '2.5I-S'; END IF;
    IF d LIKE '%2.5I-L%' THEN RETURN '2.5I-L'; END IF;
    IF d LIKE '%2.5I-PREMIUM%' THEN RETURN '2.5I-PREMIUM'; END IF;
    IF d LIKE '%2.5I%' THEN RETURN '2.5I'; END IF;
    RETURN 'BASE';
  END IF;

  -- SUBARU OUTBACK
  IF m = 'SUBARU' AND mo = 'OUTBACK' THEN
    IF d LIKE '%3.6R%' THEN RETURN '3.6R'; END IF;
    IF d LIKE '%2.5I-S%' THEN RETURN '2.5I-S'; END IF;
    IF d LIKE '%2.5I-PREMIUM%' THEN RETURN '2.5I-PREMIUM'; END IF;
    IF d LIKE '%2.5I%' THEN RETURN '2.5I'; END IF;
    RETURN 'BASE';
  END IF;

  -- HYUNDAI TUCSON
  IF m = 'HYUNDAI' AND mo = 'TUCSON' THEN
    IF d LIKE '%HIGHLANDER%' THEN RETURN 'HIGHLANDER'; END IF;
    IF d LIKE '%ELITE%' THEN RETURN 'ELITE'; END IF;
    IF d LIKE '%ACTIVE%' THEN RETURN 'ACTIVE'; END IF;
    RETURN 'BASE';
  END IF;

  -- HYUNDAI I30
  IF m = 'HYUNDAI' AND (mo = 'I30' OR mo = 'I-30') THEN
    IF d ~ '\mN\M' THEN RETURN 'N'; END IF;
    IF d LIKE '%ELITE%' THEN RETURN 'ELITE'; END IF;
    IF d LIKE '%ACTIVE%' THEN RETURN 'ACTIVE'; END IF;
    IF d LIKE '%GO%' THEN RETURN 'GO'; END IF;
    RETURN 'BASE';
  END IF;

  -- HYUNDAI SANTA FE
  IF m = 'HYUNDAI' AND mo LIKE '%SANTA FE%' THEN
    IF d LIKE '%HIGHLANDER%' THEN RETURN 'HIGHLANDER'; END IF;
    IF d LIKE '%ELITE%' THEN RETURN 'ELITE'; END IF;
    IF d LIKE '%ACTIVE%' THEN RETURN 'ACTIVE'; END IF;
    RETURN 'BASE';
  END IF;

  -- KIA SPORTAGE
  IF m = 'KIA' AND mo = 'SPORTAGE' THEN
    IF d LIKE '%GT-LINE%' THEN RETURN 'GT-LINE'; END IF;
    IF d LIKE '%SX+%' OR d LIKE '%SX PLUS%' THEN RETURN 'SX+'; END IF;
    IF d LIKE '%SX%' THEN RETURN 'SX'; END IF;
    IF d LIKE '%SI%' THEN RETURN 'SI'; END IF;
    IF d ~ '\mS\M' THEN RETURN 'S'; END IF;
    RETURN 'BASE';
  END IF;

  -- KIA CERATO
  IF m = 'KIA' AND mo = 'CERATO' THEN
    IF d LIKE '%GT%' THEN RETURN 'GT'; END IF;
    IF d LIKE '%SPORT%' THEN RETURN 'SPORT'; END IF;
    IF d LIKE '%SX%' THEN RETURN 'SX'; END IF;
    IF d ~ '\mS\M' THEN RETURN 'S'; END IF;
    RETURN 'BASE';
  END IF;

  -- HONDA CR-V
  IF m = 'HONDA' AND (mo = 'CR-V' OR mo = 'CRV') THEN
    IF d LIKE '%VTI-LX%' THEN RETURN 'VTI-LX'; END IF;
    IF d LIKE '%VTI-L%' THEN RETURN 'VTI-L'; END IF;
    IF d LIKE '%VTI-S%' THEN RETURN 'VTI-S'; END IF;
    IF d LIKE '%VTI%' THEN RETURN 'VTI'; END IF;
    RETURN 'BASE';
  END IF;

  -- HOLDEN COLORADO
  IF m = 'HOLDEN' AND mo = 'COLORADO' THEN
    IF d LIKE '%Z71%' THEN RETURN 'Z71'; END IF;
    IF d LIKE '%LTZ%' THEN RETURN 'LTZ'; END IF;
    IF d LIKE '%LT%' THEN RETURN 'LT'; END IF;
    IF d LIKE '%LS%' THEN RETURN 'LS'; END IF;
    RETURN 'BASE';
  END IF;

  -- HOLDEN COMMODORE
  IF m = 'HOLDEN' AND mo = 'COMMODORE' THEN
    IF d LIKE '%SS-V%' OR d LIKE '%SSV%' THEN RETURN 'SS-V'; END IF;
    IF d LIKE '%SS%' THEN RETURN 'SS'; END IF;
    IF d LIKE '%SV6%' THEN RETURN 'SV6'; END IF;
    IF d LIKE '%RS%' THEN RETURN 'RS'; END IF;
    IF d LIKE '%LT%' THEN RETURN 'LT'; END IF;
    RETURN 'BASE';
  END IF;

  -- HOLDEN CAPTIVA / CRUZE / TRAX
  IF m = 'HOLDEN' AND mo IN ('CAPTIVA', 'CRUZE', 'TRAX') THEN
    IF d LIKE '%LTZ%' THEN RETURN 'LTZ'; END IF;
    IF d LIKE '%LT%' THEN RETURN 'LT'; END IF;
    IF d LIKE '%LS%' THEN RETURN 'LS'; END IF;
    RETURN 'BASE';
  END IF;

  -- Fallback: return BASE for everything not explicitly handled
  RETURN 'BASE';

END;
$$;

-- BACKFILL: Set all NULL trim_class to BASE
UPDATE vehicle_sales_truth
SET trim_class = 'BASE'
WHERE trim_class IS NULL;

-- BACKFILL: Set all UNKNOWN trim_class to BASE
UPDATE vehicle_sales_truth
SET trim_class = 'BASE'
WHERE trim_class = 'UNKNOWN';
