
CREATE OR REPLACE FUNCTION public.derive_trim_from_text(
  p_make TEXT,
  p_model TEXT,
  p_description TEXT
)
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
  m TEXT := UPPER(TRIM(COALESCE(p_make,'')));
  mo TEXT := UPPER(TRIM(COALESCE(p_model,'')));
  d TEXT := UPPER(COALESCE(p_description,''));
BEGIN

  -- TOYOTA LANDCRUISER
  IF m = 'TOYOTA' AND mo = 'LANDCRUISER' THEN
    IF d LIKE '%WORKMATE%' THEN RETURN 'WORKMATE'; END IF;
    IF d LIKE '%GXL%' THEN RETURN 'GXL'; END IF;
    IF d LIKE '%GX%' THEN RETURN 'GX'; END IF;
    IF d LIKE '%VX%' THEN RETURN 'VX'; END IF;
    IF d LIKE '%SAHARA%' THEN RETURN 'SAHARA'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  -- PRADO
  IF m = 'TOYOTA' AND mo LIKE '%PRADO%' THEN
    IF d LIKE '%KAKADU%' THEN RETURN 'KAKADU'; END IF;
    IF d LIKE '%GXL%' THEN RETURN 'GXL'; END IF;
    IF d LIKE '%GX%' THEN RETURN 'GX'; END IF;
    IF d LIKE '%VX%' THEN RETURN 'VX'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  -- HILUX
  IF m = 'TOYOTA' AND mo = 'HILUX' THEN
    IF d LIKE '%ROGUE%' THEN RETURN 'ROGUE'; END IF;
    IF d LIKE '%RUGGED%' THEN RETURN 'RUGGED'; END IF;
    IF d LIKE '%SR5%' THEN RETURN 'SR5'; END IF;
    IF d LIKE '%WORKMATE%' THEN RETURN 'WORKMATE'; END IF;
    IF d ~ '\mSR\M' THEN RETURN 'SR'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  -- RAV4
  IF m = 'TOYOTA' AND mo = 'RAV4' THEN
    IF d LIKE '%EDGE%' THEN RETURN 'EDGE'; END IF;
    IF d LIKE '%CRUISER%' THEN RETURN 'CRUISER'; END IF;
    IF d LIKE '%GXL%' THEN RETURN 'GXL'; END IF;
    IF d LIKE '%GX%' THEN RETURN 'GX'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  -- KLUGER
  IF m = 'TOYOTA' AND mo = 'KLUGER' THEN
    IF d LIKE '%GRANDE%' THEN RETURN 'GRANDE'; END IF;
    IF d LIKE '%GXL%' THEN RETURN 'GXL'; END IF;
    IF d LIKE '%GX%' THEN RETURN 'GX'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  -- HIACE
  IF m = 'TOYOTA' AND mo LIKE '%HIACE%' THEN
    IF d LIKE '%COMMUTER%' THEN RETURN 'COMMUTER'; END IF;
    IF d LIKE '%SLWB%' THEN RETURN 'SLWB'; END IF;
    IF d LIKE '%LWB%' THEN RETURN 'LWB'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  -- FORD RANGER
  IF m = 'FORD' AND mo = 'RANGER' THEN
    IF d LIKE '%RAPTOR%' THEN RETURN 'RAPTOR'; END IF;
    IF d LIKE '%WILDTRAK%' THEN RETURN 'WILDTRAK'; END IF;
    IF d LIKE '%XLT%' THEN RETURN 'XLT'; END IF;
    IF d LIKE '%XLS%' THEN RETURN 'XLS'; END IF;
    IF d ~ '\mXL\M' THEN RETURN 'XL'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  -- FORD EVEREST
  IF m = 'FORD' AND mo = 'EVEREST' THEN
    IF d LIKE '%TREMOR%' THEN RETURN 'TREMOR'; END IF;
    IF d LIKE '%PLATINUM%' THEN RETURN 'PLATINUM'; END IF;
    IF d LIKE '%SPORT%' THEN RETURN 'SPORT'; END IF;
    IF d LIKE '%TITANIUM%' THEN RETURN 'TITANIUM'; END IF;
    IF d LIKE '%TREND%' THEN RETURN 'TREND'; END IF;
    IF d LIKE '%AMBIENTE%' THEN RETURN 'AMBIENTE'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  -- MAZDA BT-50
  IF m = 'MAZDA' AND (mo = 'BT-50' OR mo = 'BT50') THEN
    IF d LIKE '%XTR%' THEN RETURN 'XTR'; END IF;
    IF d ~ '\mXT\M' THEN RETURN 'XT'; END IF;
    IF d ~ '\mGT\M' THEN RETURN 'GT'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  -- VOLKSWAGEN AMAROK
  IF m = 'VOLKSWAGEN' AND mo = 'AMAROK' THEN
    IF d LIKE '%PANAMERICANA%' THEN RETURN 'PANAMERICANA'; END IF;
    IF d LIKE '%AVENTURA%' THEN RETURN 'AVENTURA'; END IF;
    IF d LIKE '%TDI550%' THEN RETURN 'TDI550'; END IF;
    IF d LIKE '%TDI400%' THEN RETURN 'TDI400'; END IF;
    IF d LIKE '%CORE%' THEN RETURN 'CORE'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  -- NISSAN PATROL
  IF m = 'NISSAN' AND mo = 'PATROL' THEN
    IF d LIKE '%TI-L%' OR d LIKE '%TIL%' THEN RETURN 'TI-L'; END IF;
    IF d ~ '\mTI\M' THEN RETURN 'TI'; END IF;
    IF d LIKE '%ST-L%' OR d LIKE '%STL%' THEN RETURN 'ST-L'; END IF;
    IF d ~ '\mST\M' THEN RETURN 'ST'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  -- NISSAN NAVARA
  IF m = 'NISSAN' AND mo = 'NAVARA' THEN
    IF d LIKE '%PRO-4X%' OR d LIKE '%PRO4X%' THEN RETURN 'PRO-4X'; END IF;
    IF d LIKE '%ST-X%' OR d LIKE '%STX%' THEN RETURN 'ST-X'; END IF;
    IF d LIKE '%ST-L%' OR d LIKE '%STL%' THEN RETURN 'ST-L'; END IF;
    IF d ~ '\mST\M' THEN RETURN 'ST'; END IF;
    IF d ~ '\mSL\M' THEN RETURN 'SL'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  -- NISSAN X-TRAIL
  IF m = 'NISSAN' AND (mo = 'X-TRAIL' OR mo = 'XTRAIL') THEN
    IF d LIKE '%TI%' THEN RETURN 'TI'; END IF;
    IF d LIKE '%ST-L%' OR d LIKE '%STL%' THEN RETURN 'ST-L'; END IF;
    IF d ~ '\mST\M' THEN RETURN 'ST'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  -- NISSAN PATHFINDER
  IF m = 'NISSAN' AND mo = 'PATHFINDER' THEN
    IF d LIKE '%TI-L%' OR d LIKE '%TIL%' THEN RETURN 'TI-L'; END IF;
    IF d ~ '\mTI\M' THEN RETURN 'TI'; END IF;
    IF d LIKE '%ST-L%' OR d LIKE '%STL%' THEN RETURN 'ST-L'; END IF;
    IF d ~ '\mST\M' THEN RETURN 'ST'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  -- ISUZU D-MAX
  IF m = 'ISUZU' AND (mo = 'D-MAX' OR mo = 'DMAX') THEN
    IF d LIKE '%X-TERRAIN%' OR d LIKE '%XTERRAIN%' THEN RETURN 'X-TERRAIN'; END IF;
    IF d LIKE '%LS-U%' OR d LIKE '%LSU%' THEN RETURN 'LS-U'; END IF;
    IF d LIKE '%LS-M%' OR d LIKE '%LSM%' THEN RETURN 'LS-M'; END IF;
    IF d ~ '\mSX\M' THEN RETURN 'SX'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  -- ISUZU MU-X
  IF m = 'ISUZU' AND (mo = 'MU-X' OR mo = 'MUX') THEN
    IF d LIKE '%LS-T%' OR d LIKE '%LST%' THEN RETURN 'LS-T'; END IF;
    IF d LIKE '%LS-U%' OR d LIKE '%LSU%' THEN RETURN 'LS-U'; END IF;
    IF d LIKE '%LS-M%' OR d LIKE '%LSM%' THEN RETURN 'LS-M'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  -- MITSUBISHI TRITON
  IF m = 'MITSUBISHI' AND mo = 'TRITON' THEN
    IF d LIKE '%GSR%' THEN RETURN 'GSR'; END IF;
    IF d LIKE '%GLS%' THEN RETURN 'GLS'; END IF;
    IF d LIKE '%GLX+%' OR d LIKE '%GLX PLUS%' THEN RETURN 'GLX+'; END IF;
    IF d LIKE '%GLX-R%' OR d LIKE '%GLXR%' THEN RETURN 'GLX-R'; END IF;
    IF d LIKE '%GLX%' THEN RETURN 'GLX'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  -- MITSUBISHI OUTLANDER
  IF m = 'MITSUBISHI' AND mo = 'OUTLANDER' THEN
    IF d LIKE '%EXCEED TOURER%' THEN RETURN 'EXCEED TOURER'; END IF;
    IF d LIKE '%EXCEED%' THEN RETURN 'EXCEED'; END IF;
    IF d LIKE '%ASPIRE%' THEN RETURN 'ASPIRE'; END IF;
    IF d ~ '\mLS\M' THEN RETURN 'LS'; END IF;
    IF d ~ '\mES\M' THEN RETURN 'ES'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  -- MITSUBISHI PAJERO SPORT
  IF m = 'MITSUBISHI' AND (mo = 'PAJERO SPORT' OR mo = 'PAJERO') THEN
    IF d LIKE '%EXCEED%' THEN RETURN 'EXCEED'; END IF;
    IF d LIKE '%GLS%' THEN RETURN 'GLS'; END IF;
    IF d LIKE '%GLX%' THEN RETURN 'GLX'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  -- MAZDA CX-5
  IF m = 'MAZDA' AND (mo = 'CX-5' OR mo = 'CX5') THEN
    IF d LIKE '%AKERA%' THEN RETURN 'AKERA'; END IF;
    IF d LIKE '%GT%' THEN RETURN 'GT'; END IF;
    IF d LIKE '%TOURING%' THEN RETURN 'TOURING'; END IF;
    IF d LIKE '%MAXX SPORT%' THEN RETURN 'MAXX SPORT'; END IF;
    IF d LIKE '%MAXX%' THEN RETURN 'MAXX'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  RETURN 'UNKNOWN';
END;
$$;
