DROP FUNCTION IF EXISTS public.derive_trim_from_text(text, text, text);

CREATE OR REPLACE FUNCTION public.derive_trim_from_text(
  p_make TEXT,
  p_model TEXT,
  p_description TEXT
)
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
  m TEXT := UPPER(TRIM(COALESCE(p_make,'')));
  mo TEXT := UPPER(TRIM(COALESCE(p_model,'')));
  d TEXT := UPPER(COALESCE(p_description,''));
BEGIN
  IF m = 'TOYOTA' AND mo = 'LANDCRUISER' THEN
    IF d LIKE '%WORKMATE%' THEN RETURN 'WORKMATE'; END IF;
    IF d LIKE '%GXL%' THEN RETURN 'GXL'; END IF;
    IF d LIKE '%GX%' THEN RETURN 'GX'; END IF;
    IF d LIKE '%VX%' THEN RETURN 'VX'; END IF;
    IF d LIKE '%SAHARA%' THEN RETURN 'SAHARA'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF m = 'TOYOTA' AND mo LIKE '%PRADO%' THEN
    IF d LIKE '%GXL%' THEN RETURN 'GXL'; END IF;
    IF d LIKE '%GX%' THEN RETURN 'GX'; END IF;
    IF d LIKE '%VX%' THEN RETURN 'VX'; END IF;
    IF d LIKE '%KAKADU%' THEN RETURN 'KAKADU'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF m = 'TOYOTA' AND mo = 'HILUX' THEN
    IF d LIKE '%WORKMATE%' THEN RETURN 'WORKMATE'; END IF;
    IF d LIKE '%SR5%' THEN RETURN 'SR5'; END IF;
    IF d LIKE '%ROGUE%' THEN RETURN 'ROGUE'; END IF;
    IF d LIKE '%RUGGED%' THEN RETURN 'RUGGED'; END IF;
    IF d LIKE '%SR%' THEN RETURN 'SR'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF m = 'TOYOTA' AND mo = 'RAV4' THEN
    IF d LIKE '%GXL%' THEN RETURN 'GXL'; END IF;
    IF d LIKE '%GX%' THEN RETURN 'GX'; END IF;
    IF d LIKE '%CRUISER%' THEN RETURN 'CRUISER'; END IF;
    IF d LIKE '%EDGE%' THEN RETURN 'EDGE'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF m = 'FORD' AND mo = 'RANGER' THEN
    IF d LIKE '%RAPTOR%' THEN RETURN 'RAPTOR'; END IF;
    IF d LIKE '%WILDTRAK%' THEN RETURN 'WILDTRAK'; END IF;
    IF d LIKE '%XLT%' THEN RETURN 'XLT'; END IF;
    IF d LIKE '%XLS%' THEN RETURN 'XLS'; END IF;
    IF d LIKE '%XL%' THEN RETURN 'XL'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF m = 'FORD' AND mo = 'EVEREST' THEN
    IF d LIKE '%AMBIENTE%' THEN RETURN 'AMBIENTE'; END IF;
    IF d LIKE '%TREND%' THEN RETURN 'TREND'; END IF;
    IF d LIKE '%TITANIUM%' THEN RETURN 'TITANIUM'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF m = 'MAZDA' AND (mo = 'BT-50' OR mo = 'BT50') THEN
    IF d LIKE '%XTR%' THEN RETURN 'XTR'; END IF;
    IF d LIKE '%XT%' THEN RETURN 'XT'; END IF;
    IF d LIKE '%GT%' THEN RETURN 'GT'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF m = 'VOLKSWAGEN' AND mo = 'AMAROK' THEN
    IF d LIKE '%AVENTURA%' THEN RETURN 'AVENTURA'; END IF;
    IF d LIKE '%PANAMERICANA%' THEN RETURN 'PANAMERICANA'; END IF;
    IF d LIKE '%TDI550%' THEN RETURN 'TDI550'; END IF;
    IF d LIKE '%CORE%' THEN RETURN 'CORE'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF m = 'NISSAN' AND mo = 'PATROL' THEN
    IF d LIKE '%ST-L%' OR d LIKE '%STL%' THEN RETURN 'ST-L'; END IF;
    IF d LIKE '%TI-L%' OR d LIKE '%TIL%' THEN RETURN 'TI-L'; END IF;
    IF d LIKE '%TI%' THEN RETURN 'TI'; END IF;
    IF d LIKE '%ST%' THEN RETURN 'ST'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF m = 'NISSAN' AND mo = 'NAVARA' THEN
    IF d LIKE '%PRO-4X%' OR d LIKE '%PRO4X%' THEN RETURN 'PRO-4X'; END IF;
    IF d LIKE '%ST-X%' OR d LIKE '%STX%' THEN RETURN 'ST-X'; END IF;
    IF d LIKE '%ST-L%' OR d LIKE '%STL%' THEN RETURN 'ST-L'; END IF;
    IF d LIKE '%SL%' THEN RETURN 'SL'; END IF;
    IF d LIKE '%ST%' THEN RETURN 'ST'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF m = 'ISUZU' AND (mo = 'D-MAX' OR mo = 'DMAX') THEN
    IF d LIKE '%X-TERRAIN%' OR d LIKE '%XTERRAIN%' THEN RETURN 'X-TERRAIN'; END IF;
    IF d LIKE '%LS-U%' OR d LIKE '%LSU%' THEN RETURN 'LS-U'; END IF;
    IF d LIKE '%LS-M%' OR d LIKE '%LSM%' THEN RETURN 'LS-M'; END IF;
    IF d LIKE '%SX%' THEN RETURN 'SX'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF m = 'ISUZU' AND (mo = 'MU-X' OR mo = 'MUX') THEN
    IF d LIKE '%LS-T%' OR d LIKE '%LST%' THEN RETURN 'LS-T'; END IF;
    IF d LIKE '%LS-U%' OR d LIKE '%LSU%' THEN RETURN 'LS-U'; END IF;
    IF d LIKE '%LS-M%' OR d LIKE '%LSM%' THEN RETURN 'LS-M'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF m = 'MITSUBISHI' AND mo = 'TRITON' THEN
    IF d LIKE '%GLX+%' OR d LIKE '%GLX PLUS%' THEN RETURN 'GLX+'; END IF;
    IF d LIKE '%GLX-R%' THEN RETURN 'GLX-R'; END IF;
    IF d LIKE '%GLX%' THEN RETURN 'GLX'; END IF;
    IF d LIKE '%GLS%' THEN RETURN 'GLS'; END IF;
    IF d LIKE '%GSR%' THEN RETURN 'GSR'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF m = 'MITSUBISHI' AND mo = 'OUTLANDER' THEN
    IF d LIKE '%EXCEED TOURER%' THEN RETURN 'EXCEED_TOURER'; END IF;
    IF d LIKE '%EXCEED%' THEN RETURN 'EXCEED'; END IF;
    IF d LIKE '%ASPIRE%' THEN RETURN 'ASPIRE'; END IF;
    IF d LIKE '%LS%' THEN RETURN 'LS'; END IF;
    IF d LIKE '%ES%' THEN RETURN 'ES'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF m = 'MITSUBISHI' AND mo = 'PAJERO SPORT' THEN
    IF d LIKE '%EXCEED%' THEN RETURN 'EXCEED'; END IF;
    IF d LIKE '%GLS%' THEN RETURN 'GLS'; END IF;
    IF d LIKE '%GLX%' THEN RETURN 'GLX'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF m = 'MITSUBISHI' AND mo = 'PAJERO' THEN
    IF d LIKE '%EXCEED%' THEN RETURN 'EXCEED'; END IF;
    IF d LIKE '%VR-X%' OR d LIKE '%VRX%' THEN RETURN 'VR-X'; END IF;
    IF d LIKE '%GLS%' THEN RETURN 'GLS'; END IF;
    IF d LIKE '%GLX%' THEN RETURN 'GLX'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF m = 'TOYOTA' AND mo = 'HIACE' THEN
    IF d LIKE '%COMMUTER%' THEN RETURN 'COMMUTER'; END IF;
    IF d LIKE '%SLWB%' THEN RETURN 'SLWB'; END IF;
    IF d LIKE '%LWB%' THEN RETURN 'LWB'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  RETURN 'UNKNOWN';
END;
$$;