
-- Add structured fingerprint columns to vehicle_sales_truth
ALTER TABLE vehicle_sales_truth
ADD COLUMN IF NOT EXISTS trim_class TEXT,
ADD COLUMN IF NOT EXISTS platform_class TEXT,
ADD COLUMN IF NOT EXISTS drivetrain_bucket TEXT;

-- Trim extraction from free text
CREATE OR REPLACE FUNCTION public.derive_trim_from_text(p_make TEXT, p_model TEXT, p_text TEXT)
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
  t TEXT := UPPER(COALESCE(p_text,''));
BEGIN
  IF p_make ILIKE 'TOYOTA' AND p_model ILIKE 'LANDCRUISER%' THEN
    IF t LIKE '%SAHARA%' THEN RETURN 'SAHARA'; END IF;
    IF t LIKE '%VX%' THEN RETURN 'VX'; END IF;
    IF t LIKE '%GXL%' THEN RETURN 'GXL'; END IF;
    IF t LIKE '%GX%' THEN RETURN 'GX'; END IF;
    IF t LIKE '%WORKMATE%' THEN RETURN 'WORKMATE'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF p_make ILIKE 'TOYOTA' AND p_model ILIKE '%PRADO%' THEN
    IF t LIKE '%KAKADU%' THEN RETURN 'KAKADU'; END IF;
    IF t LIKE '%VX%' THEN RETURN 'VX'; END IF;
    IF t LIKE '%GXL%' THEN RETURN 'GXL'; END IF;
    IF t LIKE '%GX%' THEN RETURN 'GX'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF p_make ILIKE 'TOYOTA' AND p_model ILIKE 'HILUX' THEN
    IF t LIKE '%SR5%' THEN RETURN 'SR5'; END IF;
    IF t LIKE '%ROGUE%' THEN RETURN 'ROGUE'; END IF;
    IF t LIKE '%RUGGED%' THEN RETURN 'RUGGED'; END IF;
    IF t LIKE '%SR%' THEN RETURN 'SR'; END IF;
    IF t LIKE '%WORKMATE%' THEN RETURN 'WORKMATE'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF p_make ILIKE 'TOYOTA' AND p_model ILIKE 'HIACE' THEN
    IF t LIKE '%COMMUTER%' THEN RETURN 'COMMUTER'; END IF;
    IF t LIKE '%SLWB%' THEN RETURN 'SLWB'; END IF;
    IF t LIKE '%LWB%' THEN RETURN 'LWB'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF p_make ILIKE 'FORD' AND p_model ILIKE 'RANGER' THEN
    IF t LIKE '%RAPTOR%' THEN RETURN 'RAPTOR'; END IF;
    IF t LIKE '%WILDTRAK%' THEN RETURN 'WILDTRAK'; END IF;
    IF t LIKE '%XLT%' THEN RETURN 'XLT'; END IF;
    IF t LIKE '%XLS%' THEN RETURN 'XLS'; END IF;
    IF t LIKE '%XL%' THEN RETURN 'XL'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF p_make ILIKE 'FORD' AND p_model ILIKE 'EVEREST' THEN
    IF t LIKE '%TITANIUM%' THEN RETURN 'TITANIUM'; END IF;
    IF t LIKE '%TREND%' THEN RETURN 'TREND'; END IF;
    IF t LIKE '%AMBIENTE%' THEN RETURN 'AMBIENTE'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF p_make ILIKE 'ISUZU' AND (p_model ILIKE 'D-MAX' OR p_model ILIKE 'DMAX') THEN
    IF t LIKE '%X-TERRAIN%' OR t LIKE '%XTERRAIN%' THEN RETURN 'X-TERRAIN'; END IF;
    IF t LIKE '%LS-U%' OR t LIKE '%LSU%' THEN RETURN 'LS-U'; END IF;
    IF t LIKE '%LS-M%' OR t LIKE '%LSM%' THEN RETURN 'LS-M'; END IF;
    IF t LIKE '%SX%' THEN RETURN 'SX'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF p_make ILIKE 'ISUZU' AND (p_model ILIKE 'MU-X' OR p_model ILIKE 'MUX') THEN
    IF t LIKE '%LS-T%' OR t LIKE '%LST%' THEN RETURN 'LS-T'; END IF;
    IF t LIKE '%LS-U%' OR t LIKE '%LSU%' THEN RETURN 'LS-U'; END IF;
    IF t LIKE '%LS-M%' OR t LIKE '%LSM%' THEN RETURN 'LS-M'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF p_make ILIKE 'MITSUBISHI' AND p_model ILIKE 'TRITON' THEN
    IF t LIKE '%GLX-R%' THEN RETURN 'GLX-R'; END IF;
    IF t LIKE '%GLS%' THEN RETURN 'GLS'; END IF;
    IF t LIKE '%GLX+%' OR t LIKE '%GLX PLUS%' THEN RETURN 'GLX+'; END IF;
    IF t LIKE '%GLX%' THEN RETURN 'GLX'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF p_make ILIKE 'MITSUBISHI' AND p_model ILIKE 'OUTLANDER' THEN
    IF t LIKE '%EXCEED TOURER%' THEN RETURN 'EXCEED_TOURER'; END IF;
    IF t LIKE '%EXCEED%' THEN RETURN 'EXCEED'; END IF;
    IF t LIKE '%ASPIRE%' THEN RETURN 'ASPIRE'; END IF;
    IF t LIKE '%LS%' THEN RETURN 'LS'; END IF;
    IF t LIKE '%ES%' THEN RETURN 'ES'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF p_make ILIKE 'NISSAN' AND p_model ILIKE 'NAVARA' THEN
    IF t LIKE '%PRO-4X%' OR t LIKE '%PRO4X%' THEN RETURN 'PRO-4X'; END IF;
    IF t LIKE '%ST-X%' OR t LIKE '%STX%' THEN RETURN 'ST-X'; END IF;
    IF t LIKE '%ST-L%' OR t LIKE '%STL%' THEN RETURN 'ST-L'; END IF;
    IF t LIKE '%ST%' THEN RETURN 'ST'; END IF;
    IF t LIKE '%SL%' THEN RETURN 'SL'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF p_make ILIKE 'NISSAN' AND p_model ILIKE 'PATROL' THEN
    IF t LIKE '%TI-L%' OR t LIKE '%TIL%' THEN RETURN 'TI-L'; END IF;
    IF t LIKE '%TI%' THEN RETURN 'TI'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF p_make ILIKE 'HOLDEN' AND p_model ILIKE 'COLORADO' THEN
    IF t LIKE '%Z71%' THEN RETURN 'Z71'; END IF;
    IF t LIKE '%LTZ%' THEN RETURN 'LTZ'; END IF;
    IF t LIKE '%LT%' THEN RETURN 'LT'; END IF;
    IF t LIKE '%LS%' THEN RETURN 'LS'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF p_make ILIKE 'HOLDEN' AND p_model ILIKE 'TRAX' THEN
    IF t LIKE '%LTZ%' THEN RETURN 'LTZ'; END IF;
    IF t LIKE '%LT%' THEN RETURN 'LT'; END IF;
    IF t LIKE '%LS%' THEN RETURN 'LS'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  IF p_make ILIKE 'SUBARU' AND p_model ILIKE 'OUTBACK' THEN
    IF t LIKE '%PREMIUM%' THEN RETURN 'PREMIUM'; END IF;
    IF t LIKE '%TOURING%' THEN RETURN 'TOURING'; END IF;
    RETURN 'UNKNOWN';
  END IF;

  RETURN 'UNKNOWN';
END;
$$;

-- Platform class (replaces the 3-arg version — model-only, no year needed for platform identity)
CREATE OR REPLACE FUNCTION public.derive_platform_class(p_make TEXT, p_model TEXT)
RETURNS TEXT
LANGUAGE plpgsql
AS $$
BEGIN
  IF p_make ILIKE 'TOYOTA' AND p_model ILIKE '%PRADO%' THEN RETURN 'PRADO'; END IF;
  IF p_make ILIKE 'TOYOTA' AND p_model ILIKE 'LANDCRUISER%' THEN RETURN 'LANDCRUISER'; END IF;
  IF p_make ILIKE 'MITSUBISHI' AND p_model ILIKE 'OUTLANDER' THEN RETURN 'OUTLANDER'; END IF;
  RETURN UPPER(COALESCE(p_make,'') || ':' || COALESCE(p_model,''));
END;
$$;

-- Drivetrain bucket
CREATE OR REPLACE FUNCTION public.derive_drive_bucket(p_text TEXT)
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
  t TEXT := UPPER(COALESCE(p_text,''));
BEGIN
  IF t LIKE '%4X4%' OR t LIKE '%4WD%' OR t LIKE '%AWD%' THEN RETURN '4WD'; END IF;
  IF t LIKE '%2WD%' OR t LIKE '%FWD%' OR t LIKE '%RWD%' THEN RETURN '2WD'; END IF;
  RETURN 'UNKNOWN';
END;
$$;
